name: Docker Image CI

on:
  workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Generate Dockerfile
      run: |
        cat > Dockerfile.test << EOF
        FROM golang:latest
        RUN echo -n $(date) > a.txt
        EOF
    - name: check Dockerfile
      run: cat Dockerfile.test
    - name: build
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/test:latest -f Dockerfile.test .
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/test:latest
